# Generated by Django 4.0.4 on 2022-05-10 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_choices', models.CharField(choices=[('Biberon (U7) : 5 ans et 6 ans', 'Biberon'), ('Debutant (U8, U9) : 7 ans, 8 ans', 'Debutant'), ('Poussin (U10, U11) : de 9 à 10 ans', 'Poussin'), ('Benjamin (U12, U13) : de 11 à 12 ans', 'Benjamin'), ('Minime (U14, U15) : de 13 à 14 ans', 'Minime'), ('Cadet (U16, U17) : de 15 à 16 ans', 'Cadet'), ('Junior (U18, U19) : de 17 à 18 ans', 'Junior'), ('Espoir (U19, U20) : de 18 à 20 ans', 'Espoir'), ('Senior', 'Senior'), ('Veteran au-delà de 35 ans', 'Veteran'), ('CDM', 'CDM')], default='Biberon (U7) : 5 ans et 6 ans', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_choice', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='A', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classement', models.CharField(max_length=20, null=True)),
                ('agenda', models.CharField(max_length=20, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.category')),
                ('coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coach', to=settings.AUTH_USER_MODEL)),
                ('coach_adj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjoint', to=settings.AUTH_USER_MODEL)),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.level')),
                ('photo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentification.photo')),
            ],
        ),
    ]
