# Generated by Django 4.0.4 on 2022-05-10 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=5000)),
                ('address', models.CharField(max_length=200)),
                ('infra', models.TextField(max_length=5000)),
                ('secretariat', models.CharField(max_length=500)),
                ('licence', models.TextField(max_length=5000)),
                ('network', models.CharField(max_length=200)),
                ('network_2', models.CharField(max_length=200)),
                ('photo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentification.photo')),
            ],
        ),
    ]
